# Generated by Django 5.2.4 on 2025-07-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_id", models.CharField(max_length=50)),
                ("study_uid", models.CharField(max_length=50)),
                ("series_uid", models.CharField(max_length=50)),
                ("image_uid", models.CharField(max_length=50)),
            ],
        ),
    ]
