# Generated by Django 5.2.4 on 2025-07-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=50)),
                ('research_group', models.CharField(max_length=5)),
                ('sex', models.CharField(max_length=5)),
                ('apoe', models.TextField()),
                ('visit_identifier', models.CharField(max_length=150)),
            ],
        ),
    ]
