# Generated by Django 5.2.4 on 2025-07-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medai', '0002_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='apoe',
            field=models.JSONField(),
        ),
    ]
